### ISSUE TITLE
Django 1.7 is insecure out of the box, make sure you use a VM for your safety

### ISSUE THREAD

**Issue by hairychris** [yunojuno/django-test#11]
Hey all,

If you are working through this technical test please be aware that starting the app and exposing your system to the internet via something like ngrok could lead to a security breach of your machine.

The easiest way forward is to use Vagrant or just do your developing in a VM. A better fix would be to upgrade to the latest version of Django with security patches installed.

Just a heads up, good luck with the test!

Edit: on closer inspection the worst you should be looking at is a DoS but it's still better to be safe than sorry, more info: https://www.cvedetails.com/vulnerability-list/vendor_id-10199/product_id-18211/version_id-179005/Djangoproject-Django-1.7.1.html

**Comment by hugorodgerbrown** [comment]
Test baseline has been update to 1.8.
